apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starbucks
  template:
    metadata:
      labels:
        app: starbucks
    spec:
      containers:
        - name: starbucks
          image: sachinpatkari/starbucks:latest
          ports:
            - containerPort: 3000
